### ISSUE TITLE
Investigate custom VM images

### ISSUE THREAD

**Issue by wbreza** [fireflies-crew/hello-api#10]
Investigate the idea of creating a custom VM image to be used as our base image.  How does this compare and contrast against a custom script to bootstrap the image.

https://docs.microsoft.com/en-us/azure/developer/ansible/vm-configure-from-azure-shared-image-gallery?tabs=ansible#create-a-vm-based-on-the-generalized-image

https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-deploy-app

**Comment by tessmichi** [comment]
consolidate with #5  ? or just remove bullets under that one that match this, and add links from it to this one (ex, whoever does vmss, should check out what Jeff started)

**Comment by tessmichi** [comment]
deleting and merging info under #5
